export const data = [
  // Cakes items
  {
    id: 1,
    name: 'cake',
    imgUrl: '/images/cake1.jpg',
    title: 'Chocolate Cake',
    description: 'Rich chocolate cake with layers of chocolate ganache.',
    longDescription: 'Indulge in the rich and velvety goodness of our Chocolate Cake. Each slice is a decadent delight filled with layers of chocolate ganache and moist cake. Perfect for chocolate lovers!',
    ingredients: 'Ingredients: Flour, sugar, cocoa powder, eggs, butter, cream, chocolate chips',
    price: 19.99,
  },
  {
    id: 2,
    name: 'cake',
    imgUrl: '/images/cake2.jpg',
    title: 'Vanilla Cake',
    description: 'Classic vanilla cake with velvety vanilla frosting.',
    longDescription: 'Experience the timeless classic, our Vanilla Cake. Made with the finest vanilla, this cake is the epitome of simplicity and deliciousness. A perfect choice for any occasion.',
    ingredients: 'Ingredients: Flour, sugar, eggs, butter, vanilla extract, cream, sprinkles',
    price: 18.49,
  },
  {
    id: 3,
    name: 'cake',
    imgUrl: '/images/cake3.jpg',
    title: 'Strawberry Shortcake',
    description: 'Delicate strawberry shortcake with fresh strawberries.',
    longDescription: "Enjoy the fresh and fruity goodness of our Strawberry Shortcake. Made with delicate layers of sponge cake and fresh strawberries, it's a delightful treat for strawberry enthusiasts.",
    ingredients: 'Ingredients: Sponge cake, strawberries, cream, sugar, vanilla extract' ,
    price: 22.99,
  },
  {
    id: 4,
    name: 'cake',
    imgUrl: '/images/cake4.jpg',
    title: 'Red Velvet Cake',
    description: 'Decadent red velvet cake with cream cheese frosting.',
    longDescription: 'Experience the rich and luxurious taste of our Red Velvet Cake. With its deep red color and cream cheese frosting, this cake is a true delight for special occasions.',
    ingredients: 'Ingredients: Flour, sugar, buttermilk, cocoa powder, vinegar, red food coloring, cream cheese',
    price: 21.99,
  },
  {
    id: 5,
    name: 'cake',
    imgUrl: '/images/cake5.jpg',
    title: 'Blueberry Lemon Cake',
    description: 'Zesty blueberry lemon cake with lemon glaze.',
    longDescription: 'Savor the perfect combination of zesty and sweet with our Blueberry Lemon Cake. Bursting with blueberries and a tangy lemon glaze, this cake is a refreshing treat.',
    ingredients: 'Ingredients: Flour, blueberries, lemon zest, sugar, butter, lemon juice',
    price: 20.69,
  },
  {
    id: 6,
    name: 'cake',
    imgUrl: '/images/cake6.jpg',
    title: 'Caramel Crunch Cake',
    description: 'Irresistible caramel crunch cake with caramel drizzle.',
    longDescription: 'Indulge in the sweet and crunchy delight of our Caramel Crunch Cake. Topped with a generous caramel drizzle, every bite is a taste of pure bliss.',
    ingredients: 'Ingredients: Flour, caramel, butter, sugar, cream, toffee bits',
    price: 22.59,
  },
  {
    id: 7,
    name: 'cake',
    imgUrl: '/images/cake7.jpg',
    title: 'Pistachio Delight Cake',
    description: 'Pistachio delight cake with pistachio cream frosting.',
    longDescription: 'Satisfy your cravings with the Pistachio Delight Cake. With its creamy pistachio frosting and perfectly baked layers, this cake is a nutty masterpiece.',
    ingredients: 'Ingredients: Flour, pistachios, butter, sugar, eggs, cream',
    price: 23.89,
  },
  {
    id: 8,
    name: 'cake',
    imgUrl: '/images/cake8.jpg',
    title: 'Mint Chocolate Dream Cake',
    description: 'Mint chocolate dream cake with chocolate mint layers.',
    longDescription: "Experience the dreamy flavors of our Mint Chocolate Dream Cake. Layers of mint and chocolate create a delightful combination that's simply irresistible.",
    ingredients: 'Ingredients: Flour, chocolate, mint extract, sugar, cream',
    price: 21.79,
  },
  {
    id: 9,
    name: 'cake',
    imgUrl: '/images/cake9.jpg',
    title: 'Raspberry Bliss Cake',
    description: 'Raspberry bliss cake with raspberry swirls and fresh berries.',
    longDescription: 'Delight in the fruity goodness of our Raspberry Bliss Cake. Swirled with fresh raspberries and topped with berries, this cake is pure bliss for raspberry lovers.',
    ingredients: 'Ingredients: Flour, raspberries, sugar, butter, eggs, cream',
    price: 23.89,
  },
  {
    id: 10,
    name: 'cake',
    imgUrl: '/images/cake10.jpg',
    title: 'Coconut Paradise Cake',
    description: 'Coconut paradise cake with shredded coconut topping.',
    longDescription: 'Escape to a tropical paradise with our Coconut Paradise Cake. Topped with shredded coconut, this cake is a taste of the tropics.',
    ingredients: 'Ingredients: Flour, coconut, sugar, butter, cream, vanilla extract',
    price: 20.69,
  },
  {
    id: 11,
    name: 'cupcake',
    imgUrl: '/images/cupcake13.jpg',
    title: 'Red Velvet Cupcake',
    description: 'Rich red velvet cupcake with cream cheese frosting.',
    longDescription: 'Indulge in the miniature delight of our Red Velvet Cupcake. Topped with cream cheese frosting, this cupcake is perfect for a sweet indulgence.',
    ingredients: 'Ingredients: Flour, cocoa powder, buttermilk, cream cheese, sugar',
    price: 2.99,
  },
  {
    id: 12,
    name: 'cupcake',
    imgUrl: '/images/cupcake1.jpg',
    title: 'Blueberry Cupcake',
    description: 'Moist blueberry cupcake bursting with fruity flavor.',
    longDescription: 'Experience the burst of fruity goodness with our Blueberry Cupcake. Made with plump blueberries, this cupcake is a taste of summer.',
    ingredients: 'Ingredients: Flour, blueberries, butter, sugar, cream',
    price: 2.69,
  },
  {
    id: 13,
    name: 'cupcake',
    imgUrl: '/images/cupcake2.jpg',
    title: 'Lemon Cupcake',
    description: 'Zesty lemon cupcake with tangy lemon frosting.',
    longDescription: 'Savor the zesty delight of our Lemon Cupcake. Topped with tangy lemon frosting, this cupcake is a citrusy treat that brightens your day.',
    ingredients: 'Ingredients: Flour, lemon zest, sugar, butter, cream, lemon juice',
    price: 2.59,
  },
  {
    id: 14,
    name: 'cupcake',
    imgUrl: '/images/cupcake3.jpg',
    title: 'Caramel Cupcake',
    description: 'Indulgent caramel cupcake drizzled with caramel sauce.',
    longDescription: 'Treat your taste buds to the indulgent sweetness of our Caramel Cupcake. Drizzled with caramel sauce, this cupcake is pure caramel goodness.',
    ingredients: 'Ingredients: Flour, caramel, sugar, butter, cream',
    price: 2.89,
  },
  {
    id: 15,
    name: 'cupcake',
    imgUrl: '/images/cupcake4.jpg',
    title: 'Pistachio Cupcake',
    description: 'Nutty pistachio cupcake with pistachio cream frosting.',
    longDescription: 'Experience the nutty delight of our Pistachio Cupcake. Topped with pistachio cream frosting, this cupcake is a delightful choice for pistachio lovers.',
    ingredients: 'Ingredients: Flour, pistachios, sugar, butter, cream',
    price: 3.19,
  },
  {
    id: 16,
    name: 'cupcake',
    imgUrl: '/images/cupcake5.jpg',
    title: 'Mint Chocolate Cupcake',
    description: 'Cool mint chocolate cupcake with chocolate chips.',
    longDescription: 'Indulge in the cool and chocolatey delight of our Mint Chocolate Cupcake. Filled with chocolate chips, this cupcake is a refreshing treat.',
    ingredients: 'Ingredients: Flour, chocolate, mint extract, sugar, butter, cream',
    price: 2.79,
  },
  {
    id: 17,
    name: 'cupcake',
    imgUrl: '/images/cupcake6.jpg',
    title: 'Raspberry Cupcake',
    description: 'Tangy raspberry cupcake with a raspberry swirl.',
    longDescription: 'Savor the tangy sweetness of our Raspberry Cupcake. Swirled with a raspberry compote, this cupcake is a delightful treat for raspberry enthusiasts.',
    ingredients: 'Ingredients: Flour, raspberries, sugar, butter, cream',
    price: 2.89,
  },
  {
    id: 18,
    name: 'cupcake',
    imgUrl: '/images/cupcake7.jpg',
    title: 'Coconut Cupcake',
    description: 'Tropical coconut cupcake topped with shredded coconut.',
    longDescription: 'Escape to the tropics with our Coconut Cupcake. Topped with shredded coconut, this cupcake is a taste of paradise.',
    ingredients: 'Ingredients: Flour, coconut, sugar, butter, cream',
    price: 2.69,
  },
  {
    id: 19,
    name: 'cupcake',
    imgUrl: '/images/cupcake8.jpg',
    title: 'Pumpkin Spice Cupcake',
    description: 'Warm pumpkin spice cupcake with cream cheese frosting.',
    longDescription: 'Warm your taste buds with our Pumpkin Spice Cupcake. Topped with cream cheese frosting, this cupcake is a perfect choice for the fall season.',
    ingredients: 'Ingredients: Flour, pumpkin, cinnamon, sugar, cream cheese, butter',
    price: 3.29,
  },
  {
    id: 20,
    name: 'cupcake',
    imgUrl: '/images/cupcake9.jpg',
    title: 'Cherry Almond Cupcake',
    description: 'Cherry almond cupcake with almond-flavored frosting.',
    longDescription: 'Indulge in the delightful flavors of our Cherry Almond Cupcake. Topped with almond-flavored frosting, this cupcake is a perfect choice for almond enthusiasts.',
    ingredients: 'Ingredients: Flour, cherries, almonds, sugar, butter, cream',
    price: 2.99,
  },
  // Cheesecake items
  {
    id: 21,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake1.jpg',
    title: 'Classic New York Cheesecake',
    description: 'Traditional New York-style cheesecake with a graham cracker crust.',
    longDescription: 'Experience the classic taste of our Classic New York Cheesecake. Made with a graham cracker crust, this cheesecake is a timeless delight.',
    ingredients: 'Ingredients: Cream cheese, graham crackers, sugar, eggs, vanilla extract',
    price: 25.99,
  },
  {
    id: 22,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake2.jpg',
    title: 'Strawberry Swirl Cheesecake',
    description: 'Creamy cheesecake swirled with sweet strawberry sauce.',
    longDescription: 'Savor the creamy goodness of our Strawberry Swirl Cheesecake. Swirled with sweet strawberry sauce, this cheesecake is a delightful choice for strawberry lovers.',
    ingredients: 'Ingredients: Cream cheese, strawberries, sugar, eggs, vanilla extract',
    price: 26.49,
  },
  {
    id: 23,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake3.jpg',
    title: 'Chocolate Chip Cookie Dough Cheesecake',
    description: 'Indulgent cheesecake loaded with chunks of cookie dough and chocolate chips.',
    longDescription: 'Indulge in the indulgent flavors of our Chocolate Chip Cookie Dough Cheesecake. Loaded with chunks of cookie dough and chocolate chips, this cheesecake is a treat for cookie dough enthusiasts.',
    ingredients: 'Ingredients: Cream cheese, cookie dough, chocolate chips, sugar, eggs, vanilla extract',
    price: 27.99,
  },
  {
    id: 24,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake4.jpg',
    title: 'Raspberry White Chocolate Cheesecake',
    description: 'Decadent cheesecake with a raspberry and white chocolate topping.',
    longDescription: 'Delight in the decadence of our Raspberry White Chocolate Cheesecake. Topped with a raspberry and white chocolate topping, this cheesecake is pure indulgence.',
    ingredients: 'Ingredients: Cream cheese, raspberries, white chocolate, sugar, eggs, vanilla extract',
    price: 28.99,
  },
  {
    id: 25,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake5.jpg',
    title: 'Blueberry Cheesecake',
    description: 'Rich blueberry cheesecake with a blueberry compote.',
    longDescription: 'Savor the richness of our Blueberry Cheesecake. Topped with a blueberry compote, this cheesecake is a delightful treat for blueberry enthusiasts.',
    ingredients: 'Ingredients: Cream cheese, blueberries, sugar, eggs, vanilla extract',
    price: 26.69,
  },
  {
    id: 26,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake6.jpg',
    title: 'Salted Caramel Cheesecake',
    description: 'Creamy cheesecake drizzled with salted caramel sauce.',
    longDescription: 'Indulge in the creamy sweetness of our Salted Caramel Cheesecake. Drizzled with salted caramel sauce, this cheesecake is a treat for caramel lovers.',
    ingredients: 'Ingredients: Cream cheese, caramel, sugar, eggs, vanilla extract',
    price: 27.59,
  },
  {
    id: 27,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake7.jpg',
    title: 'Turtle Cheesecake',
    description: 'Turtle cheesecake with caramel, chocolate, and pecans.',
    longDescription: 'Delight in the indulgence of our Turtle Cheesecake. Topped with caramel, chocolate, and pecans, this cheesecake is a true delight for turtle lovers.',
    ingredients: 'Ingredients: Cream cheese, caramel, chocolate, pecans, sugar, eggs, vanilla extract',
    price: 29.89,
  },
  {
    id: 28,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake8.jpg',
    title: 'Lemon Raspberry Swirl Cheesecake',
    description: 'Tangy lemon cheesecake swirled with raspberry sauce.',
    longDescription: 'Savor the tangy and fruity flavors of our Lemon Raspberry Swirl Cheesecake. Swirled with raspberry sauce, this cheesecake is a delightful choice for citrus and raspberry enthusiasts.',
    ingredients: 'Ingredients: Cream cheese, raspberries, lemon zest, sugar, eggs, vanilla extract',
    price: 27.79,
  },
  {
    id: 29,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake9.jpg',
    title: 'Pumpkin Cheesecake',
    description: 'Creamy pumpkin cheesecake with a spiced graham cracker crust.',
    longDescription: 'Warm your taste buds with our Pumpkin Cheesecake. Made with a spiced graham cracker crust, this cheesecake is the perfect treat for the fall season.',
    ingredients: 'Ingredients: Cream cheese, pumpkin, graham crackers, sugar, eggs, vanilla extract',
    price: 28.89,
  },
  {
    id: 30,
    name: 'cheesecake',
    imgUrl: '/images/cheesecake10.jpg',
    title: 'Chocolate Hazelnut Cheesecake',
    description: 'Irresistible chocolate hazelnut cheesecake with a Nutella drizzle.',
    longDescription: "Indulge in the irresistible flavors of our Chocolate Hazelnut Cheesecake. Drizzled with Nutella, this cheesecake is a chocolate and hazelnut lover's dream.",
    ingredients: 'Ingredients: Cream cheese, chocolate, hazelnuts, Nutella, sugar, eggs, vanilla extract',
    price: 26.69,
  },
  {
    id: 31,
    name: 'cookie',
    imgUrl: '/images/cookie1.jpg',
    title: 'Chocolate Chip Cookies',
    description: 'Classic chocolate chip cookies with soft and chewy centers.',
    longDescription: 'Satisfy your chocolate cravings with our Chocolate Chip Cookies. These cookies have soft and chewy centers with a perfect balance of chocolate chips in every bite.',
    ingredients: 'Ingredients: Flour, chocolate chips, butter, sugar, eggs, vanilla extract',
    price: 9.99,
  },
  {
    id: 32,
    name: 'cookie',
    imgUrl: '/images/cookie2.jpg',
    title: 'Oatmeal Raisin Cookies',
    description: 'Homemade oatmeal raisin cookies with a touch of cinnamon.',
    longDescription: 'Enjoy the comforting flavors of our Oatmeal Raisin Cookies. These homemade cookies are infused with the warmth of cinnamon and studded with plump raisins.',
    ingredients: 'Ingredients: Flour, oats, raisins, butter, sugar, eggs, cinnamon',
    price: 10.49,
  },
  {
    id: 33,
    name: 'cookie',
    imgUrl: '/images/cookie3.jpg',
    title: 'Double Chocolate Cookies',
    description: 'Double the chocolate, double the delight in these rich cookies.',
    longDescription: 'Indulge in the richness of our Double Chocolate Cookies. These cookies are double the delight with an extra dose of chocolate in every bite.',
    ingredients: 'Ingredients: Flour, cocoa powder, chocolate chips, butter, sugar, eggs, vanilla extract',
    price: 11.99,
  },
  {
    id: 34,
    name: 'cookie',
    imgUrl: '/images/cookie4.jpg',
    title: 'Peanut Butter Cookies',
    description: 'Classic peanut butter cookies with a crisscross pattern.',
    longDescription: 'Satisfy your peanut butter cravings with our classic Peanut Butter Cookies. These cookies feature the classic crisscross pattern and a rich peanut butter flavor.',
    ingredients: 'Ingredients: Flour, peanut butter, butter, sugar, eggs, vanilla extract',
    price: 10.99,
  },
  {
    id: 35,
    name: 'cookie',
    imgUrl: '/images/cookie5.jpg',
    title: 'Snickerdoodle Cookies',
    description: 'Cinnamon-sugar coated snickerdoodle cookies with a hint of vanilla.',
    longDescription: 'Experience the delightful flavors of our Snickerdoodle Cookies. These cookies are coated in cinnamon-sugar with a hint of vanilla for a comforting treat.',
    ingredients: 'Ingredients: Flour, sugar, butter, cinnamon, vanilla extract',
    price: 9.69,
  },
  {
    id: 36,
    name: 'cookie',
    imgUrl: '/images/cookie6.jpg',
    title: 'Macadamia Nut Cookies',
    description: 'Buttery macadamia nut cookies with white chocolate chips.',
    longDescription: 'Indulge in the nutty delight of our Macadamia Nut Cookies. These cookies are loaded with buttery macadamia nuts and white chocolate chips.',
    ingredients: 'Ingredients: Flour, macadamia nuts, white chocolate chips, butter, sugar, eggs, vanilla extract',
    price: 11.59,
  },
  {
    id: 37,
    name: 'cookie',
    imgUrl: '/images/cookie7.jpg',
    title: "'M&M's Cookies",
    description: "Colorful M&M's candies in every bite of these delightful cookies.",
    longDescription: "Add a pop of color to your day with our 'M&M's Cookies. These delightful cookies are filled with colorful M&M's candies in every bite.",
    ingredients: 'Ingredients: Flour, M&M\'s candies, butter, sugar, eggs, vanilla extract',
    price: 12.89,
  },
  {
    id: 38,
    name: 'cookie',
    imgUrl: '/images/cookie8.jpg',
    title: 'Gingerbread Cookies',
    description: 'Festive gingerbread cookies with icing for the holiday season.',
    longDescription: 'Celebrate the holiday season with our festive Gingerbread Cookies. These cookies are decorated with sweet icing and perfect for sharing with loved ones.',
    ingredients: 'Ingredients: Flour, ginger, molasses, butter, sugar, eggs, vanilla extract',
    price: 10.79,
  },
  {
    id: 39,
    name: 'cookie',
    imgUrl: '/images/cookie8.jpg',
    title: 'Gingerbread Cookies',
    description: 'Festive gingerbread cookies with icing for the holiday season.',
    longDescription: 'Celebrate the holiday season with our festive Gingerbread Cookies. These cookies are decorated with sweet icing and perfect for sharing with loved ones.',
    ingredients: 'Ingredients: Flour, ginger, molasses, butter, sugar, eggs, vanilla extract',
    price: 10.79,
  },
  {
    id: 40,
    name: 'cookie',
    imgUrl: '/images/cookie9.jpg',
    title: 'Coconut Macaroons',
    description: 'Chewy coconut macaroons dipped in chocolate for a sweet treat.',
    longDescription: 'Satisfy your coconut cravings with our Coconut Macaroons. These chewy coconut macaroons are dipped in chocolate for an extra sweet and delightful treat.',
    ingredients: 'Ingredients: Coconut, chocolate, sugar, eggs, vanilla extract',
    price: 11.89,
  },
  {
    id: 41,
    name: 'cookie',
    imgUrl: '/images/cookie10.jpg',
    title: 'White Chocolate Cranberry Cookies',
    description: 'White chocolate and dried cranberries make these cookies extra special.',
    longDescription: 'Enjoy the extra special flavors of our White Chocolate Cranberry Cookies. These cookies feature the sweetness of white chocolate and the tartness of dried cranberries.',
    ingredients: 'Ingredients: White chocolate, dried cranberries, butter, sugar, eggs, vanilla extract',
    price: 10.69,
  },
  ];
  


