export const data = [
  //cakes items
  {
    name: 'cake',
    imgUrl: '/images/cake1.jpg',
    title: 'Chocolate Cake',
    description: 'Rich chocolate cake with layers of chocolate ganache.',
    price: 19.99,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake2.jpg',
    title: 'Vanilla Cake',
    description: 'Classic vanilla cake with velvety vanilla frosting.',
    price: 18.49,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake3.jpg',
    title: 'Strawberry Shortcake',
    description: 'Delicate strawberry shortcake with fresh strawberries.',
    price: 22.99,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake4.jpg',
    title: 'Red Velvet Cake',
    description: 'Decadent red velvet cake with cream cheese frosting.',
    price: 21.99,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake5.jpg',
    title: 'Blueberry Lemon Cake',
    description: 'Zesty blueberry lemon cake with lemon glaze.',
    price: 20.69,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake6.jpg',
    title: 'Caramel Crunch Cake',
    description: 'Irresistible caramel crunch cake with caramel drizzle.',
    price: 22.59,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake7.jpg',
    title: 'Pistachio Delight Cake',
    description: 'Pistachio delight cake with pistachio cream frosting.',
    price: 23.89,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake8.jpg',
    title: 'Mint Chocolate Dream Cake',
    description: 'Mint chocolate dream cake with chocolate mint layers.',
    price: 21.79,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake9.jpg',
    title: 'Raspberry Bliss Cake',
    description: 'Raspberry bliss cake with raspberry swirls and fresh berries.',
    price: 23.89,
  },
  {
    name: 'cake',
    imgUrl: '/images/cake10.jpg',
    title: 'Coconut Paradise Cake',
    description: 'Coconut paradise cake with shredded coconut topping.',
    price: 20.69,
  },

  // Cupcakes
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake13.jpg',
      title: 'Red Velvet Cupcake',
      description: 'Rich red velvet cupcake with cream cheese frosting.',
      price: 2.99,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake1.jpg',
      title: 'Blueberry Cupcake',
      description: 'Moist blueberry cupcake bursting with fruity flavor.',
      price: 2.69,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake2.jpg',
      title: 'Lemon Cupcake',
      description: 'Zesty lemon cupcake with tangy lemon frosting.',
      price: 2.59,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake3.jpg',
      title: 'Caramel Cupcake',
      description: 'Indulgent caramel cupcake drizzled with caramel sauce.',
      price: 2.89,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake4.jpg',
      title: 'Pistachio Cupcake',
      description: 'Nutty pistachio cupcake with pistachio cream frosting.',
      price: 3.19,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake5.jpg',
      title: 'Mint Chocolate Cupcake',
      description: 'Cool mint chocolate cupcake with chocolate chips.',
      price: 2.79,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake6.jpg',
      title: 'Raspberry Cupcake',
      description: 'Tangy raspberry cupcake with a raspberry swirl.',
      price: 2.89,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake7.jpg',
      title: 'Coconut Cupcake',
      description: 'Tropical coconut cupcake topped with shredded coconut.',
      price: 2.69,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake8.jpg',
      title: 'Pumpkin Spice Cupcake',
      description: 'Warm pumpkin spice cupcake with cream cheese frosting.',
      price: 3.29,
    },
    {
      name: 'cupcake',
      imgUrl: '/images/cupcake9.jpg',
      title: 'Cherry Almond Cupcake',
      description: 'Cherry almond cupcake with almond-flavored frosting.',
      price: 2.99,
    },
    
    //cheesecake items
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake1.jpg',
      title: 'Classic New York Cheesecake',
      description: 'Traditional New York-style cheesecake with a graham cracker crust.',
      price: 25.99,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake2.jpg',
      title: 'Strawberry Swirl Cheesecake',
      description: 'Creamy cheesecake swirled with sweet strawberry sauce.',
      price: 26.49,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake3.jpg',
      title: 'Chocolate Chip Cookie Dough Cheesecake',
      description: 'Indulgent cheesecake loaded with chunks of cookie dough and chocolate chips.',
      price: 27.99,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake4.jpg',
      title: 'Raspberry White Chocolate Cheesecake',
      description: 'Decadent cheesecake with a raspberry and white chocolate topping.',
      price: 28.99,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake5.jpg',
      title: 'Blueberry Cheesecake',
      description: 'Rich blueberry cheesecake with a blueberry compote.',
      price: 26.69,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake6.jpg',
      title: 'Salted Caramel Cheesecake',
      description: 'Creamy cheesecake drizzled with salted caramel sauce.',
      price: 27.59,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake7.jpg',
      title: 'Turtle Cheesecake',
      description: 'Turtle cheesecake with caramel, chocolate, and pecans.',
      price: 29.89,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake8.jpg',
      title: 'Lemon Raspberry Swirl Cheesecake',
      description: 'Tangy lemon cheesecake swirled with raspberry sauce.',
      price: 27.79,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake9.jpg',
      title: 'Pumpkin Cheesecake',
      description: 'Creamy pumpkin cheesecake with a spiced graham cracker crust.',
      price: 28.89,
    },
    {
      name: 'cheesecake',
      imgUrl: '/images/cheesecake10.jpg',
      title: 'Chocolate Hazelnut Cheesecake',
      description: 'Irresistible chocolate hazelnut cheesecake with a Nutella drizzle.',
      price: 26.69,
    },
    //cookies items
    {
      name: 'cookie',
      imgUrl: '/images/cookie1.jpg',
      title: 'Chocolate Chip Cookies',
      description: 'Classic chocolate chip cookies with soft and chewy centers.',
      price: 9.99,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie2.jpg',
      title: 'Oatmeal Raisin Cookies',
      description: 'Homemade oatmeal raisin cookies with a touch of cinnamon.',
      price: 10.49,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie3.jpg',
      title: 'Double Chocolate Cookies',
      description: 'Double the chocolate, double the delight in these rich cookies.',
      price: 11.99,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie4.jpg',
      title: 'Peanut Butter Cookies',
      description: 'Classic peanut butter cookies with a crisscross pattern.',
      price: 10.99,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie5.jpg',
      title: 'Snickerdoodle Cookies',
      description: 'Cinnamon-sugar coated snickerdoodle cookies with a hint of vanilla.',
      price: 9.69,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie6.jpg',
      title: 'Macadamia Nut Cookies',
      description: 'Buttery macadamia nut cookies with white chocolate chips.',
      price: 11.59,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie7.jpg',
      title: "'M&M's Cookies",
      description: "Colorful M&M's candies in every bite of these delightful cookies.",
      price: 12.89,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie8.jpg',
      title: 'Gingerbread Cookies',
      description: 'Festive gingerbread cookies with icing for the holiday season.',
      price: 10.79,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie9.jpg',
      title: 'Coconut Macaroons',
      description: 'Chewy coconut macaroons dipped in chocolate for a sweet treat.',
      price: 11.89,
    },
    {
      name: 'cookie',
      imgUrl: '/images/cookie10.jpg',
      title: 'White Chocolate Cranberry Cookies',
      description: 'White chocolate and dried cranberries make these cookies extra special.',
      price: 10.69,
    },
  ];
  